parameters:
#    acme_question.example.class: Acme\QuestionBundle\Example

services:
#    acme_question.example:
#        class: %acme_question.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
